FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN [ "python", "-c", "import nltk; nltk.download('stopwords')" ]

COPY ./app /code/app
COPY ./static /code/static


CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
